default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

development:
  <<: *default
  compile: true
  extract_css: false

test:
  <<: *default
  compile: true
  extract_css: false

production:
  <<: *default
  compile: false
  extract_css: true
